=== concrain/decks/groovy-tests/classes/production/IntroGroovy/xml/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
    xmlns="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.kousenit.com/books" 
    xmlns:tns="http://www.kousenit.com/books" 
    elementFormDefault="qualified">

    <element name="library" type="tns:LibraryType" />
    <complexType name="LibraryType">
        <sequence>
            <element ref="tns:book" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <element name="book">
        <complexType>
            <sequence>
                <element name="title" type="string" />
                <element name="author" type="string" maxOccurs="unbounded" />
                <element name="price" type="tns:PriceType" />
            </sequence>
            <attribute name="isbn" type="tns:ISBNtype" />
        </complexType>
    </element>
    <simpleType name="PriceType">
        <restriction base="decimal">
            <fractionDigits value="2" />
        </restriction>
    </simpleType>
    <simpleType name="ISBNtype">
        <restriction base="string">
            <pattern value="\d{10}|\d{13}" />
        </restriction>
    </simpleType>
</schema>

=== concrain/decks/groovy-tests/src/main/groovy/xml/books.xml
<?xml version="1.0" encoding="UTF-8" ?>
<library
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.kousenit.com/books"
    xsi:schemaLocation="
        http://www.kousenit.com/books 
        books.xsd">
	<book isbn="9781935182443">
		<title>Groovy in Action</title>
		<author>Dierk Koenig</author>
		<price>39.99</price>
	</book>
	<book isbn="9781935182948">
		<title>Making Java Groovy</title>
		<author>Ken Kousen</author>
		<price>35.99</price>
	</book>
	<book isbn="9781935182238">
		<title>Griffon in Action</title>
		<author>Andres Almiray</author>
		<price>35.99</price>
	</book>
	<book isbn="1933988932">
		<title>Grails in Action</title>
		<author>Glen Smith</author>
		<price>27.50</price>
	</book>
</library>
